#!/usr/bin/env ruby

require 'image_science'

ImageScience.with_image(ARGV[0]) do |img|
  height = img.width / 16 * 9
  img.with_crop(0, img.height - height, img.width, img.height) do |c|
    c.save(ARGV[1])
  end
end