#!/usr/bin/env ruby

require 'open-uri'


HOST = 'http://ljh.me:10037'

id = ARGV[0]
path = File.join('/tmp', id + '.simple_lock')

exit if !File.exists?(path)
key = IO.read(path)

url = "#{HOST}/unlock/#{id}/#{key.strip}"

response = open(url).read

if response.strip == '1'
	# succeeded
	File.unlink(path)
end
