#!/usr/bin/env ruby

require 'open-uri'

HOST = 'http://ljh.me:10037'

id = ARGV[0]
url = "#{HOST}/lock/#{id}"
path = File.join('/tmp', id + '.simple_lock')

response = open(url).read

if response.strip != '0'
	# succeeded
	IO.write(path, response)
end
